### ISSUE TITLE
Can't open dynamic library: Error 126: The specified module could not be found.

### ISSUE THREAD

**Issue by lucaslcode** [godotengine/godot-git-plugin#20]
I get the following with the v1.1 release on Windows 10 x64, Godot 3.2 stable

```
ERROR: Can't open dynamic library: D:/path/to/project/bin/win64/libgitapi.dll, error: Error 126: The specified module could not be found.
.
   At: platform/windows/os_windows.cpp:2269
```

The file is indeed at the path printed. Is there some dependency that I might be missing? (If so this should be documented.)

**Comment by IronicallySerious** [comment]
This is a bug, there is no library that needs to be included. Related to #11

**Comment by IronicallySerious** [comment]
I will be making a new release later this day. It should be fixed on master.

**Comment by IronicallySerious** [comment]
This issue did apppear once on my Windows 10, however since then it hasn't appeared even once. Tried things that could break it (disabling, enabling, deleting generated .git folder, etc.)

**Comment by lucaslcode** [comment]
Still happens for me including on a fresh project. Is there any way I can help debug?

**Comment by lucaslcode** [comment]
I was able to fix it. I checked the dll dependencies and I didn't have vcruntime140_1.dll despite having vcruntime140.dll. I installed the latest [2019 VC Redistributable here ](https://support.microsoft.com/en-gb/help/2977003/the-latest-supported-visual-c-downloads)and it worked.

**Comment by IronicallySerious** [comment]
@lucaslcode Thanks for finding the issue. I will add this to the installation instructions

**Comment by jwt74** [comment]
This problem went away when I added .git*,git_api* to the exclude field under the resource tab of the export window.  Installing visual studio did not make any difference for me.

**Comment by IronicallySerious** [comment]
@jwt74 I think that way the plugin itself might be ignored by the engine. Are you still able to commit using the UI?

And please mention your plugin version, and which VC++ runtime have you installed. The correct version in mentioned in the wiki.
