### ISSUE TITLE
Crash in Godot 3.x branch 

### ISSUE THREAD

**Issue by qarmin** [godotengine/godot-git-plugin#61]
Godot 3.3.rc.custom_build. 22e8fe7bf
Ubuntu  20.04

Running empty project and trying to initialize vcs, crashes with this info

```
modules/gdnative/gdnative/array.cpp:49:2: runtime error: constructor call on misaligned address 0x6060005006d2 for type 'struct Array', which requires 8 byte alignment
0x6060005006d2: note: pointer points here
 be be  be be be be be be be be  be be be be be be be be  be be be be be be be be  be be be be be be
              ^ 
core/array.cpp:471:5: runtime error: member access within misaligned address 0x6060005006d2 for type 'struct Array', which requires 8 byte alignment
0x6060005006d2: note: pointer points here
 be be  be be be be be be be be  be be be be be be be be  be be be be be be be be  be be be be be be
              ^ 
core/array.cpp:472:2: runtime error: member access within misaligned address 0x6060005006d2 for type 'struct Array', which requires 8 byte alignment
0x6060005006d2: note: pointer points here
 be be  be be e0 bd 7c 01 40 60  00 00 be be be be be be  be be be be be be be be  be be be be be be
              ^ 
handle_crash: Program crashed with signal 11
Dumping the backtrace. Please include this when reporting the bug on https://github.com/godotengine/godot/issues
[1] godots() [0x1737270] (/mnt/Miecz/godot3.2/platform/x11/crash_handler_x11.cpp:54)
[2] /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7fead12da210] (??:0)
[3] /home/rafal/Downloads/godot-git-plugin-v1.2.1-x11/bin/x11/release/libgitapi.so(git_repository_is_bare+0x36) [0x7fea80b20194] (??:0)
[4] /home/rafal/Downloads/godot-git-plugin-v1.2.1-x11/bin/x11/release/libgitapi.so(+0x2c37b7) [0x7fea80b267b7] (??:0)
[5] /home/rafal/Downloads/godot-git-plugin-v1.2.1-x11/bin/x11/release/libgitapi.so(git_status_list_new+0x136) [0x7fea80b26fd9] (??:0)
[6] godot::GitAPI::_get_modified_files_data() (??:0)
[7] godot_variant godot::__wrapped_method<godot::GitAPI, godot::Dictionary>(void*, void*, void*, int, godot_variant**) (??:0)
[8] NativeScriptInstance::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/modules/gdnative/nativescript/nativescript.cpp:709)
[9] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:898 (discriminator 1))
[10] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot3.2/core/object.cpp:846)
[11] EditorVCSInterface::get_modified_files_data() (/mnt/Miecz/godot3.2/editor/editor_vcs_interface.cpp:122 (discriminator 1))
[12] VersionControlEditorPlugin::_refresh_stage_area() (/mnt/Miecz/godot3.2/editor/plugins/version_control_editor_plugin.cpp:171 (discriminator 1))
[13] VersionControlEditorPlugin::_initialize_vcs() (/mnt/Miecz/godot3.2/editor/plugins/version_control_editor_plugin.cpp:137)
[14] MethodBind0::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:61 (discriminator 4))
[15] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[16] Object::emit_signal(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/core/object.cpp:1246 (discriminator 1))
[17] Object::emit_signal(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot3.2/core/object.cpp:1303)
[18] BaseButton::_pressed() (/mnt/Miecz/godot3.2/scene/gui/base_button.cpp:135 (discriminator 1))
[19] BaseButton::on_action_event(Ref<InputEvent>) (/mnt/Miecz/godot3.2/scene/gui/base_button.cpp:174)
[20] BaseButton::_gui_input(Ref<InputEvent>) (/mnt/Miecz/godot3.2/scene/gui/base_button.cpp:64 (discriminator 3))
[21] MethodBind1<Ref<InputEvent> >::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:775 (discriminator 12))
[22] Object::call_multilevel(StringName const&, Variant const**, int) (/mnt/Miecz/godot3.2/core/object.cpp:761 (discriminator 1))
[23] Object::call_multilevel(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot3.2/core/object.cpp:862)
[24] Viewport::_gui_call_input(Control*, Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/scene/main/viewport.cpp:1716 (discriminator 1))
[25] Viewport::_gui_input_event(Ref<InputEvent>) (/mnt/Miecz/godot3.2/scene/main/viewport.cpp:2103 (discriminator 3))
[26] Viewport::input(Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/scene/main/viewport.cpp:2923 (discriminator 2))
[27] Viewport::_vp_input(Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/scene/main/viewport.cpp:1480)
[28] MethodBind1<Ref<InputEvent> const&>::call(Object*, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/./core/method_bind.gen.inc:775 (discriminator 12))
[29] Object::call(StringName const&, Variant const**, int, Variant::CallError&) (/mnt/Miecz/godot3.2/core/object.cpp:919 (discriminator 1))
[30] Object::call(StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot3.2/core/object.cpp:846)
[31] SceneTree::call_group_flags(unsigned int, StringName const&, StringName const&, Variant const&, Variant const&, Variant const&, Variant const&, Variant const&) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:276)
[32] SceneTree::input_event(Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/scene/main/scene_tree.cpp:432 (discriminator 5))
[33] InputDefault::_parse_input_event_impl(Ref<InputEvent> const&, bool) (/mnt/Miecz/godot3.2/main/input_default.cpp:429)
[34] InputDefault::parse_input_event(Ref<InputEvent> const&) (/mnt/Miecz/godot3.2/main/input_default.cpp:273)
[35] InputDefault::flush_accumulated_events() (/mnt/Miecz/godot3.2/main/input_default.cpp:692)
[36] OS_X11::process_xevents() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:2337)
[37] OS_X11::run() (/mnt/Miecz/godot3.2/platform/x11/os_x11.cpp:3639)
[38] godots(main+0x326) [0x172defc] (/mnt/Miecz/godot3.2/platform/x11/godot_x11.cpp:57)
[39] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fead12bb0b3] (??:0)
[40] godots(_start+0x2e) [0x172db1e] (??:?)
```

**Comment by ChronicallySerious** [comment]
It doesn't seem like the plugin is causing this. Probably that the GDNative API for Godot 3.3rc's might be incompatible with Godot 3.2.x's GDNative API

**Comment by ChronicallySerious** [comment]
If yes then it probably can be solved by re-compiling against the (official or custom generated) Godot 3.3rc (or the upcoming stable version) GDNative C++ API

**Comment by ChronicallySerious** [comment]
Could you also post the plugin version you are using?

I have not been able to reproduce this on plugin v1.2 and Godot 3.3rc

**Comment by qarmin** [comment]
I downloaded the latest 1.2.1 version for linux - https://github.com/godotengine/godot-git-plugin/releases/download/v1.2.1/godot-git-plugin-v1.2.1-x11.zip

**Comment by akien-mga** [comment]
This was likely fixed by https://github.com/godotengine/godot/pull/47623 (and further refined with https://github.com/godotengine/godot/pull/47655), please confirm.

**Comment by qarmin** [comment]
Crash still happens with 3.3.rc.custom_build. `e97cd3d52`

It is only visible when running Godot with address sanitizer (`scons use_asan=yes`) on Linux and probably macOS

**Comment by ChronicallySerious** [comment]
Can confirm that this doesn't appear on windows with `use_asan` as well.

**Comment by Janglee123** [comment]
I cant reproduce this on v3.3.stable.custom_build on linux.

**Comment by qarmin** [comment]
I can still reproduce crash with latest 3.x branch
You can use this precompiled binaries(compiled on Ubuntu 20.04 - `scons use_ubsan=yes use_asan=yes`) - https://github.com/qarmin/godot/releases/download/address/godot.x11.tools.64s.zip

**Comment by ChronicallySerious** [comment]
The Godot 3.5 beta1 is now live. And along with it, we released a v2.0.0 of this plugin which should fix this issue. Since I wasn't able to reproduce this error, I wasn't able to confirm if the crash has been fixed, so you may re-open this issue if the error prevails. 

We fixed a lot of memory leaks and uninitialized memory errors with v2.0.0, so there is high chance that this is now fixed.
